name: Deploy 

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências e fazer o Build
        run: |
          npm ci
          npm run build --configuration=production

      - name: Enviar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/mnidrums-site/browser/
          server-dir: ./mnidrums-ftp/
